### ISSUE TITLE
No Following Found

### ISSUE THREAD

**Issue by HappyFishkeeper** [mattlehrer/whomtofollow#1]
Whom to Follow isn't working for me.  It's telling me:

We tried and could not get the list of accounts you follow. Either you don't follow any accounts yet (check out [FediPages](https://fedipages.com/) to find some) or you have the "Hide your social graph" setting checked in [your Mastodon profile settings](https://mastodon.social/settings/profile):

I don't have "hide your social graph checked".

Followgraph is working for me, in contrast.

I'm on mstdn.party and my handle is @MattChambers.

**Comment by mattlehrer** [comment]
I tried to reproduce this yesterday and today and it has been working for me, searching for your account. What browser / operating system are you using?

**Comment by HappyFishkeeper** [comment]
Thank you. I am using Vivaldi browser with Windows 10.

 

I was thinking that it might have something to do with my instance, because I read yesterday that the admin of mstdn.party is missing not responding to inquiries. The fact that you were able to search for my account suggests otherwise, of course.

 

I will try again today (unless I decide to move instances).

**Comment by mattlehrer** [comment]
I did see that about mstdn.party and the admin. I wonder if the instance had a hiccup when you tried. I hope that was it but please let me know if you still have trouble and I will try to figure out a solution.

**Comment by HappyFishkeeper** [comment]
It is working now. I switched to a different instance (Vivaldi), but I don't know if that is what fixed it. Thanks again for your help.

**Comment by mattlehrer** [comment]
Glad to hear, thanks for letting me know.
